# Generated by Django 4.1.7 on 2023-03-24 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pais",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pais", models.CharField(max_length=50)),
                ("codigo", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Salario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bruto", models.DecimalField(decimal_places=2, max_digits=8)),
                ("extra_diciembre", models.BooleanField()),
                ("extra_junio", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Puesto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(max_length=1000)),
                (
                    "salario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empresa.salario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Localizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                (
                    "pais",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="empresa.pais"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fabrica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("direccion", models.CharField(max_length=250)),
                ("codigo_postal", models.CharField(max_length=10)),
                (
                    "localizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empresa.localizacion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Empleado",
            fields=[
                ("nombre", models.CharField(max_length=30)),
                ("apellido", models.CharField(max_length=30)),
                (
                    "dni",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                (
                    "fabrica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empresa.fabrica",
                    ),
                ),
                (
                    "puesto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="empresa.puesto"
                    ),
                ),
            ],
        ),
    ]
